#server:
#  port: 8081
#spring:
#  application:
#    name: vehicle-service
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#


server:
  port: 8082
spring:
  application:
      name: VEHICLE-SERVICE
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/