#spring.application.name=config-server

#server:
#  port: 8088
#spring:
#  profiles:
#    active: native


server:
  port: 8088
spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: native

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/