server:
  port: 8085
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id: VEHICLE-SERVICE
            uri: lb://VEHICLE-SERVICE
            predicates:
              - Path=/api/v1/vehicle/**
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/v1/user/**
          - id: TICKET-SERVICE
            uri: lb://TICKET-SERVICE
            predicates:
              - Path=/api/v1/payment/**
          - id: PAYMENT-SERVICE
            uri: lb://PAYMENT-SERVICE
            predicates:
              - Path=/api/v1/ticket/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



